add_test( [==[Tactic 1]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 1]==]  )
set_tests_properties( [==[Tactic 1]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 2]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 2]==]  )
set_tests_properties( [==[Tactic 2]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 3]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 3]==]  )
set_tests_properties( [==[Tactic 3]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 4]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 4]==]  )
set_tests_properties( [==[Tactic 4]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 5]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 5]==]  )
set_tests_properties( [==[Tactic 5]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 6]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 6]==]  )
set_tests_properties( [==[Tactic 6]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 7]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 7]==]  )
set_tests_properties( [==[Tactic 7]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 1 Time-Limited]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 1 Time-Limited]==]  )
set_tests_properties( [==[Tactic 1 Time-Limited]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 2 Time-Limited]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 2 Time-Limited]==]  )
set_tests_properties( [==[Tactic 2 Time-Limited]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 3 Time-Limited]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 3 Time-Limited]==]  )
set_tests_properties( [==[Tactic 3 Time-Limited]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 4 Time-Limited]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 4 Time-Limited]==]  )
set_tests_properties( [==[Tactic 4 Time-Limited]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 5 Time-Limited]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 5 Time-Limited]==]  )
set_tests_properties( [==[Tactic 5 Time-Limited]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 6 Time-Limited]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 6 Time-Limited]==]  )
set_tests_properties( [==[Tactic 6 Time-Limited]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
add_test( [==[Tactic 7 Time-Limited]==] /tmp/lamano_famB/build_champ/tests/release_tactics_tests [==[Tactic 7 Time-Limited]==]  )
set_tests_properties( [==[Tactic 7 Time-Limited]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_champ/tests)
set( release_tactics_tests_TESTS [==[Tactic 1]==] [==[Tactic 2]==] [==[Tactic 3]==] [==[Tactic 4]==] [==[Tactic 5]==] [==[Tactic 6]==] [==[Tactic 7]==] [==[Tactic 1 Time-Limited]==] [==[Tactic 2 Time-Limited]==] [==[Tactic 3 Time-Limited]==] [==[Tactic 4 Time-Limited]==] [==[Tactic 5 Time-Limited]==] [==[Tactic 6 Time-Limited]==] [==[Tactic 7 Time-Limited]==])
