add_test( [==[Repetition: winning side avoids the draw]==] /tmp/lamano_famB/build_nosplit/tests/repetition_tests [==[Repetition: winning side avoids the draw]==]  )
set_tests_properties( [==[Repetition: winning side avoids the draw]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[Repetition: losing side forces the perpetual draw]==] /tmp/lamano_famB/build_nosplit/tests/repetition_tests [==[Repetition: losing side forces the perpetual draw]==]  )
set_tests_properties( [==[Repetition: losing side forces the perpetual draw]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[Repetition: long perpetual is also forced to a draw]==] /tmp/lamano_famB/build_nosplit/tests/repetition_tests [==[Repetition: long perpetual is also forced to a draw]==]  )
set_tests_properties( [==[Repetition: long perpetual is also forced to a draw]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[Repetition: non-king shuffle history, winning side]==] /tmp/lamano_famB/build_nosplit/tests/repetition_tests [==[Repetition: non-king shuffle history\, winning side]==]  )
set_tests_properties( [==[Repetition: non-king shuffle history, winning side]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
set( repetition_tests_TESTS [==[Repetition: winning side avoids the draw]==] [==[Repetition: losing side forces the perpetual draw]==] [==[Repetition: long perpetual is also forced to a draw]==] [==[Repetition: non-king shuffle history, winning side]==])
