if(EXISTS "/tmp/lamano_famB/build_nosplit/tests/uci_tests-b12d07c_tests.cmake")
  include("/tmp/lamano_famB/build_nosplit/tests/uci_tests-b12d07c_tests.cmake")
else()
  add_test(uci_tests_NOT_BUILT-b12d07c uci_tests_NOT_BUILT-b12d07c)
endif()
