add_test( [==[UCI handshake responds with id and uciok]==] /tmp/lamano_famB/build_nosplit/tests/uci_tests [==[UCI handshake responds with id and uciok]==]  )
set_tests_properties( [==[UCI handshake responds with id and uciok]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[UCI isready responds with readyok]==] /tmp/lamano_famB/build_nosplit/tests/uci_tests [==[UCI isready responds with readyok]==]  )
set_tests_properties( [==[UCI isready responds with readyok]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[UCI ignores unknown commands and keeps responding]==] /tmp/lamano_famB/build_nosplit/tests/uci_tests [==[UCI ignores unknown commands and keeps responding]==]  )
set_tests_properties( [==[UCI ignores unknown commands and keeps responding]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[UCI accepts position startpos with moves]==] /tmp/lamano_famB/build_nosplit/tests/uci_tests [==[UCI accepts position startpos with moves]==]  )
set_tests_properties( [==[UCI accepts position startpos with moves]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[UCI accepts position fen]==] /tmp/lamano_famB/build_nosplit/tests/uci_tests [==[UCI accepts position fen]==]  )
set_tests_properties( [==[UCI accepts position fen]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[UCI accepts setoption commands]==] /tmp/lamano_famB/build_nosplit/tests/uci_tests [==[UCI accepts setoption commands]==]  )
set_tests_properties( [==[UCI accepts setoption commands]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[UCI quit stops the loop before later commands]==] /tmp/lamano_famB/build_nosplit/tests/uci_tests [==[UCI quit stops the loop before later commands]==]  )
set_tests_properties( [==[UCI quit stops the loop before later commands]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
add_test( [==[UCI full game round trip produces a bestmove]==] /tmp/lamano_famB/build_nosplit/tests/uci_tests [==[UCI full game round trip produces a bestmove]==]  )
set_tests_properties( [==[UCI full game round trip produces a bestmove]==] PROPERTIES WORKING_DIRECTORY /tmp/lamano_famB/build_nosplit/tests)
set( uci_tests_TESTS [==[UCI handshake responds with id and uciok]==] [==[UCI isready responds with readyok]==] [==[UCI ignores unknown commands and keeps responding]==] [==[UCI accepts position startpos with moves]==] [==[UCI accepts position fen]==] [==[UCI accepts setoption commands]==] [==[UCI quit stops the loop before later commands]==] [==[UCI full game round trip produces a bestmove]==])
